on:
  push:
    branches:
      - master
      - develop

steps:
- uses: actions/checkout@master
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '2.2.402' # SDK Version to use.
- run: dotnet build <my project>