name: build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' # SDK Version to use.
    - name: test
      run: dotnet test lutos-api.sln
    - name: build
      run: dotnet test lutos-api.sln

