name: ci

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    path:
      - '*.cs'
      - '*.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' # SDK Version to use.
    - name: test
      run: dotnet test lutos-api.sln
